template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-Stranger}

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9001

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: onePassword@123
  url: jdbc:mysql://localhost:3306/testdb
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    charSet: utf8mb4


#  CREATE DATABASE `testdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
