server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9001

database:
  driverClass: com.mysql.jdbc.Driver
  user: jana
  password: jana@123
  url: jdbc:mysql://localhost:3306/schema2
  properties:
    charSet: UTF-8